name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone/Checkout Code
      uses: actions/checkout@v4 

    - name: Set Up Docker
      uses: actions/setup-python@v5

    - name: Build Docker Image
      run: docker build -t events-api .

    - name: Run Container
      run: docker run -d -p 5001:5001 --name events-api-container events-api

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Install Requirements
      run: pip install --no-cache-dir -r requirements.txt

    - name: Run Tests
      run: pytest -v

    - name: Stop And Remove Containers
      if: always()
      run: |
        docker stop events-api-container
        docker rm events-api-container
    
